disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name

opt_in_rules:
- empty_count
- unused_private_declaration
- prohibited_interface_builder
- modifier_order
- file_name
- first_where
- fatal_error_message
- empty_string

included:
- SimpleCounter
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods

force_cast: warning
force_try:
  severity: warning
empty_count:
  severity: warning

nesting:
  type_level: 4
line_length: 300
file_length:
  warning: 1000
  error: 2000
function_body_length:
  warning: 200
  error: 500
cyclomatic_complexity:
  warning: 10
  error: 50
type_body_length:
  warning: 200
  error: 1000
large_tuple:
  warning: 4
  error: 5
identifier_name:
  min_length: 1
  max_length:
    warning: 60
    error: 80
type_name:
  min_length: 2
  max_length:
    warning: 50
    error: 60
